### ISSUE TITLE
¿qué le falta a este proyecto para que sea deployable en mxabierto?

### ISSUE THREAD

**Issue by defvol** [GobiernoFacil/evaluacion_ciudadana#10]
Lo que salga de esta discusión terminará en -> https://github.com/GobiernoFacil/evaluacion_ciudadana/wiki/Requerimientos-para-integraci%C3%B3n

**Comment by defvol** [comment]
Un Dockerfile

**Comment by defvol** [comment]
Leer variables desde ambiente, ver [/example.keys.php](https://github.com/GobiernoFacil/evaluacion_ciudadana/blob/6601db73b1c898421cd8ce614f169d6044f979c1/example.keys.php)

**Comment by bcessa** [comment]
De manera general los puntos importantes deberían ser:
- La aplicación debe tener un punto de arranque ( entry point ) bien definido
- Preferentemente alguna forma deterministica de instarla, junto con sus dependencias
- Debe proveer valores por default aceptables para los parámetros de configuración requeridos pero permitir sobre-escribirlos a través de variables de ambiente y de forma explicita mediante argumentos al punto de arranque o archivo de configuración
- Debería correr un solo proceso, en caso de no ser posible, manejar de forma interna el direccionamiento de las señales entre los procesos involucrados
- Direccionar la información de salida en algún forma estructurado a la salida estándar; a partir de ahí se puede redireccionar fácilmente a otro destino ( archivo de log, DB, agente, etc ) y/o formatear de distintas formas
- Manejar los escenarios de arranque, re-inicio y terminación de forma apropiada

**Comment by defvol** [comment]
:+1: @bcessa 

Agregaría que en caso de que utilice DBMS u otros componentes estos vivan en otro contenedor y se liguen mediante `docker --link`

**Comment by defvol** [comment]
En términos generales son estos principios: https://github.com/mxabierto/hackea-el-sistema/wiki/Proyecto-Cero:-sobre-deployments

¿Pero en términos específicos de esta app?
