### ISSUE TITLE
Para todas las acciones realizadas por el usuario poner una leyenda  de que esta “completada la acción con éxito” o en caso contrario que   muestre “error en la captura”.

### ISSUE THREAD

**Issue by hugovom** [GobiernoFacil/evaluacion_ciudadana#32]

**Comment by elcoruco** [comment]
![captura de pantalla 2016-01-30 a las 11 54 54 p m](https://cloud.githubusercontent.com/assets/3756555/12700532/1075d976-c7ad-11e5-9ff9-85900e26f9f2.png)

Ya te pregunta si deseas eliminar la encuesta.

![captura de pantalla 2016-01-30 a las 11 55 46 p m](https://cloud.githubusercontent.com/assets/3756555/12700535/1cc3c5bc-c7ad-11e5-892b-c11cbf1bf63f.png)

El código está en views/wackyland/surveys_view.php

**Comment by elcoruco** [comment]
@hugovom 
En encuestas, cuando se logra eliminar una, aparece un div con la clase success/error después del menú principal. Este div está en el header del administrador.
![captura de pantalla 2016-01-31 a las 12 09 46 a m](https://cloud.githubusercontent.com/assets/3756555/12700598/2f414b04-c7af-11e5-8bbb-3b01ea51d30e.png)

Los textos se definen en el controller.
![captura de pantalla 2016-01-31 a las 12 09 58 a m](https://cloud.githubusercontent.com/assets/3756555/12700599/3212c31c-c7af-11e5-85f7-84e8cd7cde9c.png)
